### ISSUE TITLE
Update to newer upstream version

### ISSUE THREAD

**Issue by p-bo** [OpenMediaVault-Plugin-Developers/openmediavault-urbackup-server#1]
Hi,
would it be possible to update package urbackup-server to more recent version, 2.2.4 ideally? I improved translation into Czech and want to use it in production.

Thanks :)

**Comment by ryecoaaron** [comment]
I don't see 2.2.4 available for download on the download page - https://hndl.urbackup.org/Server/

**Comment by p-bo** [comment]
You are right - must admit, that now am a bit confused about versing of this software:
https://github.com/uroni/urbackup_backend/releases - 2.2.4 (2.1.19 even isn't here...)
Will ask UrBackup author - for now sorry for reporting something you cannot resolve.
Will update about my findings.
Thanks :-)

**Comment by p-bo** [comment]
In FAQ and documentation it wasn't covered, but on forum there was answer:
https://forums.urbackup.org/t/urbackup-server-2-2-4-beta-restore-2-1-1-beta/3890
So first there must be RC and then 2.2.x release. According dates of previous releases, it could be pretty soon.
If you are watching final releases regularly, then please close this bug, otherwise what about to keep it as a reminder?

**Comment by ryecoaaron** [comment]
We can leave it.  I don't check for new releases a lot.  So, if you see a release, you can let me know here.

**Comment by Akruidenberg** [comment]
new version is there. (2.1.20) please update the deb package.

**Comment by ryecoaaron** [comment]
2.1.20 has been in the OMV 4.x repo for weeks.  Last I read, that package didn't work on OMV 3.x.  If you have evidence telling me it does work on OMV 3.x, I can put it in the repo.

**Comment by kirkbaum** [comment]
Would you mind updating this package to  version 2.4.11.  Thank you for providing this package.

**Comment by ryecoaaron** [comment]
2.4.11 in repo now.
