### ISSUE TITLE
Dependency wrong for Debian9 stretch

### ISSUE THREAD

**Issue by Miarka24** [OpenMediaVault-Plugin-Developers/openmediavault-urbackup-server#2]
Its not possible to install this plugin in arrakis on debian stretch.
The following dependency must be changed:
libcrypto++9 -> libcrypto++6

**Comment by ryecoaaron** [comment]
If I remember correctly, I added it because it was not a dependency of the urbackup package but it is now.  So, the dependency was removed since the plugin itself does not need libcrypto.  New package (3.1) in erasmus and arrakis repos.
